# Generated by Django 6.0.5 on 2026-05-20 22:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('engine', models.CharField(choices=[('legacy', 'Legacy BFS engine'), ('scrapy', 'Scrapy spider')], default='legacy', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='running', max_length=16)),
                ('seed_url', models.URLField(blank=True, default='', max_length=2048)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('pages_attempted', models.IntegerField(default=0)),
                ('pages_ok', models.IntegerField(default=0)),
                ('pages_errored', models.IntegerField(default=0)),
                ('health_score', models.IntegerField(blank=True, null=True)),
                ('health_tier', models.CharField(blank=True, default='', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['-started_at'], name='crawler_cra_started_ebfcb8_idx'), models.Index(fields=['status', '-started_at'], name='crawler_cra_status_10f4e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrawlerPageResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('final_url', models.URLField(blank=True, default='', max_length=2048)),
                ('status_code', models.CharField(blank=True, default='', max_length=4)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('word_count', models.IntegerField(default=0)),
                ('error_type', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('subdomain', models.CharField(blank=True, default='', max_length=64)),
                ('page_type', models.CharField(blank=True, default='', max_length=64)),
                ('category_key', models.CharField(blank=True, default='', max_length=128)),
                ('from_sitemap', models.BooleanField(default=False)),
                ('indexed_status', models.CharField(choices=[('indexed', 'Indexed'), ('not_indexed', 'Not indexed'), ('excluded', 'Excluded'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('pagespeed_score', models.IntegerField(blank=True, null=True)),
                ('lcp_ms', models.IntegerField(blank=True, null=True)),
                ('cls', models.FloatField(blank=True, null=True)),
                ('inp_ms', models.IntegerField(blank=True, null=True)),
                ('static_word_count', models.IntegerField(blank=True, null=True)),
                ('rendered_word_count', models.IntegerField(blank=True, null=True)),
                ('playwright_used', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='crawler.crawlsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='CrawlIssue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('issue_slug', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('notice', 'Notice')], default='warning', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='crawler.crawlerpageresult')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='crawler.crawlsnapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['snapshot', 'issue_slug'], name='crawler_cra_snapsho_4d0c82_idx'), models.Index(fields=['snapshot', 'severity'], name='crawler_cra_snapsho_21c6ac_idx'), models.Index(fields=['snapshot', 'category'], name='crawler_cra_snapsho_7783ab_idx'), models.Index(fields=['url', '-detected_at'], name='crawler_cra_url_9ff833_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='crawlerpageresult',
            index=models.Index(fields=['snapshot', 'status_code'], name='crawler_cra_snapsho_09f1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerpageresult',
            index=models.Index(fields=['snapshot', 'subdomain'], name='crawler_cra_snapsho_0cc320_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerpageresult',
            index=models.Index(fields=['snapshot', 'page_type'], name='crawler_cra_snapsho_bf45c9_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerpageresult',
            index=models.Index(fields=['snapshot', 'indexed_status'], name='crawler_cra_snapsho_496f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerpageresult',
            index=models.Index(fields=['snapshot', '-word_count'], name='crawler_cra_snapsho_ce43d4_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerpageresult',
            index=models.Index(fields=['snapshot', '-response_time_ms'], name='crawler_cra_snapsho_76a26a_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlerpageresult',
            index=models.Index(fields=['url', '-fetched_at'], name='crawler_cra_url_74009f_idx'),
        ),
        migrations.AddConstraint(
            model_name='crawlerpageresult',
            constraint=models.UniqueConstraint(fields=('snapshot', 'url'), name='uniq_pageresult_snapshot_url'),
        ),
    ]
