# Generated by Django 6.0.2 on 2026-02-25 09:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(db_index=True, help_text='Primary domain name (e.g. example.com)', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='Human-readable name for the website', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the crawler should actively process this website')),
                ('include_subdomains', models.BooleanField(default=False, help_text='Whether to include subdomain crawling')),
            ],
            options={
                'verbose_name_plural': 'websites',
                'db_table': 'websites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotsRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_content', models.TextField(blank=True, default='', help_text='Raw robots.txt file content')),
                ('disallowed_paths', models.JSONField(default=list, help_text='List of disallowed paths extracted from robots.txt')),
                ('allowed_paths', models.JSONField(default=list, help_text='List of explicitly allowed paths')),
                ('crawl_delay', models.FloatField(blank=True, help_text='Crawl-delay directive value (seconds)', null=True)),
                ('sitemap_urls', models.JSONField(default=list, help_text='Sitemap URLs discovered from robots.txt')),
                ('fetched_at', models.DateTimeField(blank=True, help_text='Timestamp of last robots.txt fetch', null=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='robots_rule', to='crawler.website')),
            ],
            options={
                'verbose_name': 'Robots.txt Rule',
                'verbose_name_plural': 'Robots.txt Rules',
                'db_table': 'robots_rules',
            },
        ),
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_depth', models.PositiveIntegerField(default=7, help_text='Maximum crawl depth (e.g., 7)')),
                ('max_urls_per_session', models.PositiveIntegerField(default=50000, help_text='Hard cap on URLs per crawl session')),
                ('concurrency', models.PositiveIntegerField(default=10, help_text='Max concurrent requests to this domain')),
                ('request_delay', models.FloatField(default=1.0, help_text='Delay (seconds) between requests for politeness')),
                ('request_timeout', models.PositiveIntegerField(default=30, help_text='HTTP request timeout in seconds')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Max retry attempts on failure')),
                ('enable_js_rendering', models.BooleanField(default=False, help_text='Use Playwright for JavaScript rendering')),
                ('respect_robots_txt', models.BooleanField(default=True, help_text='Whether to obey robots.txt rules')),
                ('custom_user_agent', models.CharField(blank=True, default='', help_text='Optional custom User-Agent string', max_length=500)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_config', to='crawler.website')),
            ],
            options={
                'verbose_name': 'Crawl Configuration',
                'verbose_name_plural': 'Crawl Configurations',
                'db_table': 'crawl_configs',
            },
        ),
    ]
