# Generated by Django 6.0.5 on 2026-05-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recorded_date', models.DateField(db_index=True)),
                ('engine', models.CharField(default='legacy', max_length=16)),
                ('health_score', models.IntegerField(blank=True, null=True)),
                ('health_tier', models.CharField(blank=True, default='', max_length=16)),
                ('pages_attempted', models.IntegerField(default=0)),
                ('pages_ok', models.IntegerField(default=0)),
                ('pages_errored', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('notices', models.IntegerField(default=0)),
                ('issue_counts', models.JSONField(blank=True, default=dict)),
                ('category_counts', models.JSONField(blank=True, default=dict)),
                ('pagerank_node_count', models.IntegerField(default=0)),
                ('pagerank_orphan_count', models.IntegerField(default=0)),
                ('near_dup_cluster_count', models.IntegerField(default=0)),
                ('near_dup_total_dupes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-recorded_date',),
                'indexes': [models.Index(fields=['-recorded_date'], name='crawler_met_recorde_58e66c_idx'), models.Index(fields=['engine', '-recorded_date'], name='crawler_met_engine_80c0f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('recorded_date', 'engine'), name='uniq_metricsnapshot_date_engine')],
            },
        ),
    ]
