# Generated by Django 6.0.5 on 2026-05-20 23:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_metricsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIBotLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField(db_index=True)),
                ('bot', models.CharField(choices=[('gptbot', 'GPTBot (OpenAI)'), ('chatgpt-user', 'ChatGPT-User (browsing)'), ('oai-searchbot', 'OAI-SearchBot'), ('claudebot', 'ClaudeBot (Anthropic)'), ('claude-user', 'Claude-User (browsing)'), ('perplexitybot', 'PerplexityBot'), ('perplexity-user', 'Perplexity-User'), ('google-extended', 'Google-Extended (Gemini)'), ('bytespider', 'Bytespider (ByteDance/Doubao)'), ('ccbot', 'CCBot (Common Crawl)'), ('meta-externalagent', 'Meta-ExternalAgent'), ('other', 'Other AI bot')], db_index=True, max_length=32)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('url', models.URLField(db_index=True, max_length=2000)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('bytes_sent', models.PositiveIntegerField(default=0)),
                ('referer', models.TextField(blank=True, default='')),
                ('raw', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-seen_at',),
                'indexes': [models.Index(fields=['-seen_at', 'bot'], name='crawler_aib_seen_at_34a646_idx'), models.Index(fields=['url', '-seen_at'], name='crawler_aib_url_a7ae08_idx'), models.Index(fields=['bot', 'verified'], name='crawler_aib_bot_3aa961_idx')],
            },
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(db_index=True, max_length=2000)),
                ('source_domain', models.CharField(db_index=True, max_length=255)),
                ('target_url', models.URLField(db_index=True, max_length=2000)),
                ('target_domain', models.CharField(db_index=True, max_length=255)),
                ('anchor_text', models.TextField(blank=True, default='')),
                ('rel', models.CharField(blank=True, default='', max_length=64)),
                ('nofollow', models.BooleanField(default=False)),
                ('discovered_in', models.CharField(db_index=True, default='manual', help_text="Common Crawl release ID (e.g. CC-MAIN-2026-09) or 'manual'.", max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-last_seen',),
                'indexes': [models.Index(fields=['target_domain', '-last_seen'], name='crawler_bac_target__6b7fa6_idx'), models.Index(fields=['source_domain', 'target_domain'], name='crawler_bac_source__d87a09_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_url', 'target_url'), name='uniq_backlink_source_target')],
            },
        ),
    ]
