# Generated by Django 6.0.5 on 2026-05-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_competitor_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_cls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_cls_category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_fcp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_has_field_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_inp_category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_inp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_lcp_category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_lcp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_pagespeed_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_si_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_tbt_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='desktop_ttfb_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_cls',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_cls_category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_fcp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_has_field_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_inp_category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_inp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_lcp_category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_lcp_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_pagespeed_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_si_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_tbt_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='mobile_ttfb_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
