# Generated by Django 6.0.5 on 2026-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_dual_strategy_cwv'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpageresult',
            name='canonical_chain_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='canonical_html',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='canonical_http',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='canonical_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='canonical_to_noindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='csp',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='has_insecure_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='has_mixed_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='hsts',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='image_audit_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='image_broken_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='image_empty_alt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='image_missing_alt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='image_oversized_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='meta_description_pixel_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='multiple_canonicals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='permissions_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='redirect_chain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='redirect_final_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='redirect_hops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='redirect_loop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='referrer_policy',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='title_pixel_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='x_content_type_options',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='x_frame_options',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
