# Generated by Django 4.2.30 on 2026-05-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_phase_a_sf_parity'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpageresult',
            name='hreflang_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='hreflang_entries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='hreflang_has_x_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='hreflang_invalid_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='hreflang_self_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='jsonld_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='jsonld_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='jsonld_invalid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='jsonld_missing_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='jsonld_rich_result_eligible',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='jsonld_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='microdata_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='rdfa_count',
            field=models.IntegerField(default=0),
        ),
    ]
