# Generated by Django 4.2.30 on 2026-05-22 07:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_phase_b_hreflang_jsonld'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpageresult',
            name='content_delta_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='custom_extracted',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='flesch_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='grade_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='js_rendered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='jsonld_delta_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='link_delta_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='pdf_author',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='pdf_byte_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='pdf_has_text_layer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='pdf_is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='pdf_language',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='pdf_page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='pdf_subject',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='pdf_title',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='readable_sentence_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='readable_word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='spelling_error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='spelling_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CustomExtractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('selector_type', models.CharField(choices=[('css', 'CSS selector'), ('xpath', 'XPath')], default='css', max_length=8)),
                ('selector', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'name'], name='crawler_cus_is_acti_9692de_idx')],
            },
        ),
    ]
