# Generated by Django 4.2.30 on 2026-05-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_phase_c_render_pdf_xpath_readability'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpageresult',
            name='amp_alternate_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='amp_canonical_target',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='amp_invalid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='amp_required_missing',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='cookie_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='cookies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='cookies_insecure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='cookies_no_httponly_session_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='cookies_no_samesite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='cookies_third_party_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='cookies_tracker_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='form_inputs_no_label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='h1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='has_amp_alternate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='has_consent_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='has_skip_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='heading_skip_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='html_lang',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='invalid_aria_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='is_amp_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='links_generic_text',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='links_no_text',
            field=models.IntegerField(default=0),
        ),
    ]
