# Generated by Django 4.2.30 on 2026-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_phase_d_cookies_amp_a11y'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpageresult',
            name='axe_tool_used',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='color_contrast_violations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='color_contrast_violations_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='grammar_categories',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='grammar_error_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='grammar_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='grammar_lang_detected',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='grammar_tool_used',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
