# Generated by Django 4.2.30 on 2026-05-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_phase_e_grammar_axe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_idx', models.IntegerField(default=0)),
                ('chunk_text', models.TextField(blank=True, default='')),
                ('embedding_json', models.JSONField(blank=True, default=list)),
                ('products', models.JSONField(blank=True, default=list)),
                ('page_type', models.CharField(blank=True, default='', max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('coord_x', models.FloatField(blank=True, null=True)),
                ('coord_y', models.FloatField(blank=True, null=True)),
                ('coord_z', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='crawler.crawlerpageresult')),
            ],
            options={
                'indexes': [models.Index(fields=['page_type'], name='crawler_pag_page_ty_45d65a_idx'), models.Index(fields=['confidence'], name='crawler_pag_confide_c683c1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pageembedding',
            constraint=models.UniqueConstraint(fields=('page', 'chunk_idx'), name='uniq_page_embedding_chunk'),
        ),
        # Ensure pgvector extension exists; add a native vector(384)
        # column alongside the JSON fallback. Similarity search uses
        # the SQL column directly via raw queries; ORM still works
        # because Django sees only the columns it created.
        migrations.RunSQL(
            sql=[
                "CREATE EXTENSION IF NOT EXISTS vector;",
                "ALTER TABLE crawler_pageembedding ADD COLUMN embedding vector(384);",
                # HNSW index for fast cosine similarity at scale.
                "CREATE INDEX crawler_pageembedding_vec_cos "
                "ON crawler_pageembedding USING hnsw (embedding vector_cosine_ops);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS crawler_pageembedding_vec_cos;",
                "ALTER TABLE crawler_pageembedding DROP COLUMN IF EXISTS embedding;",
            ],
        ),
    ]
