# Generated by Django 4.2.30 on 2026-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_phase2_page_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpageresult',
            name='external_links_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='headings_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='images_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='internal_links_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
