# Generated by Django 4.2.30 on 2026-06-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0016_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerpageresult',
            name='indexability_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='indexability_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='is_indexable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crawlerpageresult',
            name='x_robots_tag',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
