# Generated by Django 4.2.30 on 2026-06-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0017_crawlerpageresult_indexability_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageEmbedding',
        ),
    ]
