# Generated by Django 6.0.5 on 2026-05-13 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEORun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('triggered_by', models.CharField(default='api', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('critic', 'Critic'), ('complete', 'Complete'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('sub_scores', models.JSONField(blank=True, default=dict)),
                ('weights', models.JSONField(blank=True, default=dict)),
                ('sources_snapshot', models.JSONField(blank=True, default=dict)),
                ('model_versions', models.JSONField(blank=True, default=dict)),
                ('total_cost_usd', models.FloatField(default=0.0)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['domain', '-started_at'], name='seo_ai_seor_domain_66b333_idx'), models.Index(fields=['status'], name='seo_ai_seor_status_f015a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SEORunFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('notice', 'Notice')], max_length=16)),
                ('category', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('impact', models.CharField(default='medium', max_length=16)),
                ('effort', models.CharField(default='medium', max_length=16)),
                ('priority', models.IntegerField(default=50)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='seo_ai.seorun')),
            ],
            options={
                'ordering': ('-priority',),
                'indexes': [models.Index(fields=['run', '-priority'], name='seo_ai_seor_run_id_709ac1_idx'), models.Index(fields=['agent'], name='seo_ai_seor_agent_ce891a_idx'), models.Index(fields=['severity'], name='seo_ai_seor_severit_f2a47a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SEORunMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.IntegerField()),
                ('from_agent', models.CharField(max_length=64)),
                ('to_agent', models.CharField(blank=True, default='', max_length=64)),
                ('role', models.CharField(max_length=32)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='seo_ai.seorun')),
            ],
            options={
                'ordering': ('run', 'step_index', 'created_at'),
                'indexes': [models.Index(fields=['run', 'step_index'], name='seo_ai_seor_run_id_ad88b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='SEORunToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent', models.CharField(max_length=64)),
                ('tool_name', models.CharField(max_length=128)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cached', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='seo_ai.seorun')),
            ],
            options={
                'ordering': ('run', 'created_at'),
                'indexes': [models.Index(fields=['run', 'agent'], name='seo_ai_seor_run_id_87c516_idx')],
            },
        ),
    ]
