# Generated by Django 6.0.5 on 2026-05-20 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ai', '0003_gapserpresult_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='GapAuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('our_url', models.URLField(max_length=2048)),
                ('their_url', models.URLField(max_length=2048)),
                ('winner', models.CharField(choices=[('us', 'Us'), ('them', 'Them'), ('tie', 'Tie')], max_length=8)),
                ('our_score', models.IntegerField(default=0)),
                ('their_score', models.IntegerField(default=0)),
                ('our_strengths', models.JSONField(blank=True, default=list)),
                ('our_gaps', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('verdict_summary', models.TextField(blank=True, default='')),
                ('rubric_version', models.CharField(default='v1', max_length=16)),
                ('llm_provider', models.CharField(default='groq', max_length=32)),
                ('llm_model', models.CharField(blank=True, default='', max_length=64)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('triggered_by', models.CharField(default='chat', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-graded_at',),
            },
        ),
        migrations.CreateModel(
            name='GapPagePair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('our_url', models.URLField(max_length=2048)),
                ('our_title', models.CharField(blank=True, default='', max_length=512)),
                ('their_url', models.URLField(max_length=2048)),
                ('their_title', models.CharField(blank=True, default='', max_length=512)),
                ('competitor_domain', models.CharField(max_length=255)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('slug_jaccard', models.FloatField(default=0.0)),
                ('title_cosine', models.FloatField(default=0.0)),
                ('match_reason', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('run', 'competitor_domain', '-similarity_score'),
            },
        ),
        migrations.RenameIndex(
            model_name='gapcomparison',
            new_name='seo_ai_gapc_run_id_062d70_idx',
            old_name='gap_pipe_cmp_run_idx',
        ),
        migrations.RenameIndex(
            model_name='gapcompetitor',
            new_name='seo_ai_gapc_run_id_3edbbd_idx',
            old_name='gap_pipe_comp_run_idx',
        ),
        migrations.RenameIndex(
            model_name='gapdeepcrawl',
            new_name='seo_ai_gapd_run_id_d5ca16_idx',
            old_name='gap_pipe_dc_run_idx',
        ),
        migrations.RenameIndex(
            model_name='gapllmresult',
            new_name='seo_ai_gapl_run_id_782b9c_idx',
            old_name='gap_pipe_llm_run_idx',
        ),
        migrations.RenameIndex(
            model_name='gapllmresult',
            new_name='seo_ai_gapl_query_i_2c8dbb_idx',
            old_name='gap_pipe_llm_q_idx',
        ),
        migrations.RenameIndex(
            model_name='gappipelinequery',
            new_name='seo_ai_gapp_run_id_c07adf_idx',
            old_name='gap_pipe_q_run_idx',
        ),
        migrations.RenameIndex(
            model_name='gappipelinerun',
            new_name='seo_ai_gapp_domain_81e355_idx',
            old_name='gap_pipe_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='gappipelinerun',
            new_name='seo_ai_gapp_status_65be08_idx',
            old_name='gap_pipe_status_idx',
        ),
        migrations.RenameIndex(
            model_name='gapserpresult',
            new_name='seo_ai_gaps_run_id_720a4f_idx',
            old_name='gap_pipe_serp_run_idx',
        ),
        migrations.RenameIndex(
            model_name='gapserpresult',
            new_name='seo_ai_gaps_run_id_cad1ab_idx',
            old_name='gap_pipe_serp_run_eng_dev_idx',
        ),
        migrations.RenameIndex(
            model_name='gapserpresult',
            new_name='seo_ai_gaps_query_i_5ab7d4_idx',
            old_name='gap_pipe_serp_q_idx',
        ),
        migrations.AddField(
            model_name='gappagepair',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_pairs', to='seo_ai.gappipelinerun'),
        ),
        migrations.AddField(
            model_name='gapauditfinding',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='seo_ai.gappagepair'),
        ),
        migrations.AddIndex(
            model_name='gappagepair',
            index=models.Index(fields=['run', 'competitor_domain'], name='seo_ai_gapp_run_id_7f4c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='gappagepair',
            index=models.Index(fields=['our_url'], name='seo_ai_gapp_our_url_22423e_idx'),
        ),
        migrations.AddIndex(
            model_name='gapauditfinding',
            index=models.Index(fields=['pair', '-graded_at'], name='seo_ai_gapa_pair_id_7ec44d_idx'),
        ),
        migrations.AddIndex(
            model_name='gapauditfinding',
            index=models.Index(fields=['our_url', '-graded_at'], name='seo_ai_gapa_our_url_108316_idx'),
        ),
    ]
