# Generated by Django 6.0.5 on 2026-05-22 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ai', '0004_gapauditfinding_gappagepair_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2000, unique=True)),
                ('source_domain', models.CharField(db_index=True, max_length=255)),
                ('source_title', models.CharField(blank=True, default='', max_length=512)),
                ('snippet', models.TextField(blank=True, default='')),
                ('brand_variant', models.CharField(choices=[('new', 'Bajaj Life Insurance (new brand)'), ('old', 'Bajaj Allianz Life (legacy brand)'), ('parent', 'Bajaj Allianz (general — ambiguous)'), ('ambiguous', 'Ambiguous / multiple')], db_index=True, default='new', max_length=16)),
                ('source_tier', models.CharField(choices=[('news_tier_1', 'News (tier 1)'), ('news_tier_2', 'News (tier 2)'), ('forum', 'Forum / community'), ('review', 'Review site'), ('aggregator', 'Insurance aggregator'), ('regulatory', 'Regulatory body'), ('blog', 'Blog / other'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('unscored', 'Unscored')], db_index=True, default='unscored', max_length=16)),
                ('sentiment_confidence', models.FloatField(default=0.0)),
                ('is_linked', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('discovered_via', models.CharField(choices=[('rss', 'RSS feed'), ('reddit', 'Reddit public JSON'), ('serpapi', 'SerpAPI daily'), ('commoncrawl', 'Common Crawl'), ('manual', 'Manual import')], default='manual', max_length=16)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-last_seen_at',),
                'indexes': [models.Index(fields=['-last_seen_at'], name='seo_ai_bran_last_se_0ea80e_idx'), models.Index(fields=['source_tier', '-last_seen_at'], name='seo_ai_bran_source__03bf39_idx'), models.Index(fields=['sentiment', '-last_seen_at'], name='seo_ai_bran_sentime_fa49cd_idx'), models.Index(fields=['brand_variant', '-last_seen_at'], name='seo_ai_bran_brand_v_b929c4_idx'), models.Index(fields=['source_domain', '-last_seen_at'], name='seo_ai_bran_source__2145f6_idx')],
            },
        ),
    ]
