# Generated by Django 6.0.5 on 2026-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ai', '0005_brand_mention'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmention',
            name='anchor_texts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='body_excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='co_mentioned_brands',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='country',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='is_topical',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='language',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='page_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='rating_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='rating_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='brandmention',
            name='topical_category',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='brandmention',
            name='is_linked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
