# Generated by Django 6.0.5 on 2026-05-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ai', '0006_brand_mention_deep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmention',
            name='source_tier',
            field=models.CharField(choices=[('owned', 'Owned property (Bajaj family)'), ('news_tier_1', 'News (tier 1)'), ('news_tier_2', 'News (tier 2)'), ('forum', 'Forum / community'), ('review', 'Review site'), ('aggregator', 'Insurance aggregator'), ('regulatory', 'Regulatory body'), ('blog', 'Blog / other'), ('other', 'Other')], db_index=True, default='other', max_length=16),
        ),
    ]
