# Generated by Django 4.2.30 on 2026-05-25 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ai', '0007_brand_mention_owned_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRewriteProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('our_url', models.URLField(max_length=2048)),
                ('competitor_urls', models.JSONField(blank=True, default=list)),
                ('target_keywords', models.JSONField(blank=True, default=list)),
                ('evidence_dict', models.JSONField(blank=True, default=dict)),
                ('raw_proposal', models.JSONField(blank=True, default=dict)),
                ('generated_proposal', models.JSONField(blank=True, default=dict)),
                ('critic_verdict', models.JSONField(blank=True, default=dict)),
                ('model_used', models.CharField(blank=True, default='', max_length=128)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='seo_ai_cont_created_df6cf9_idx'), models.Index(fields=['our_url', '-created_at'], name='seo_ai_cont_our_url_8e2bfd_idx')],
            },
        ),
    ]
