# Generated by Django 4.2.30 on 2026-05-26 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ai', '0008_content_rewrite_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPageHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('competitor_domain', models.CharField(db_index=True, max_length=255)),
                ('seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('snapshot_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=1024)),
                ('meta_description', models.CharField(blank=True, default='', max_length=1024)),
                ('word_count', models.IntegerField(default=0)),
                ('heading_count', models.IntegerField(default=0)),
                ('internal_link_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('title_hash', models.CharField(db_index=True, max_length=64)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('structure_hash', models.CharField(db_index=True, max_length=64)),
                ('delta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-seen_at',),
                'indexes': [models.Index(fields=['url', '-seen_at'], name='seo_ai_comp_url_460309_idx'), models.Index(fields=['competitor_domain', '-seen_at'], name='seo_ai_comp_competi_8ed524_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompetitorChangeEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('competitor_domain', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(choices=[('new', 'Newly discovered URL'), ('title', 'Title changed'), ('content', 'Body content changed'), ('structure', 'Page structure changed'), ('removed', 'URL gone (404 / drop)')], max_length=16)),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delta', models.JSONField(blank=True, default=dict)),
                ('from_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_events', to='seo_ai.competitorpagehistory')),
                ('to_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_events', to='seo_ai.competitorpagehistory')),
            ],
            options={
                'ordering': ('-detected_at',),
                'indexes': [models.Index(fields=['competitor_domain', '-detected_at'], name='seo_ai_comp_competi_09022d_idx'), models.Index(fields=['kind', '-detected_at'], name='seo_ai_comp_kind_71bd0f_idx'), models.Index(fields=['url', '-detected_at'], name='seo_ai_comp_url_276ae7_idx')],
            },
        ),
    ]
