# Generated by Django 4.2.30 on 2026-05-31 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ai', '0013_content_writer_structures'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandmention',
            name='prominence_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='gappipelinequery',
            name='source',
            field=models.CharField(default='seed', max_length=16),
        ),
        migrations.CreateModel(
            name='GapEntityGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('our_url', models.URLField(max_length=2048)),
                ('our_entities', models.JSONField(blank=True, default=list)),
                ('missing_entities', models.JSONField(blank=True, default=list)),
                ('wikidata', models.JSONField(blank=True, default=dict)),
                ('audit_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_gaps', to='seo_ai.gappipelinerun')),
            ],
            options={
                'ordering': ('run', 'our_url'),
            },
        ),
        migrations.CreateModel(
            name='AICrawlerDirective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, default='bajajlifeinsurance.com', max_length=255)),
                ('bot', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('disallow', 'Disallow')], default='allow', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('domain', 'bot'),
                'unique_together': {('domain', 'bot')},
            },
        ),
        migrations.CreateModel(
            name='GapLLMVisibilitySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('our_mention_rate', models.FloatField(default=0.0)),
                ('web_grounded_rate', models.FloatField(default=0.0)),
                ('total_calls', models.IntegerField(default=0)),
                ('competitor_rates', models.JSONField(blank=True, default=dict)),
                ('provider_breakdown', models.JSONField(blank=True, default=dict)),
                ('ai_bot_hits_30d', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visibility_snapshots', to='seo_ai.gappipelinerun')),
            ],
            options={
                'ordering': ('-taken_at',),
                'indexes': [models.Index(fields=['domain', '-taken_at'], name='seo_ai_gapl_domain_8b03eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='GapContentOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('our_url', models.URLField(max_length=2048)),
                ('current_score', models.IntegerField(default=0)),
                ('target_score', models.IntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('missing_schema', models.JSONField(blank=True, default=list)),
                ('priority', models.IntegerField(db_index=True, default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_optimizations', to='seo_ai.gappipelinerun')),
            ],
            options={
                'ordering': ('run', '-priority'),
                'indexes': [models.Index(fields=['run', '-priority'], name='seo_ai_gapc_run_id_992bb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='GapCitationGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('our_url', models.URLField(max_length=2048)),
                ('our_citation_count', models.IntegerField(default=0)),
                ('competitor_citation_median', models.IntegerField(default=0)),
                ('gap_estimate', models.IntegerField(default=0)),
                ('priority', models.IntegerField(db_index=True, default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_gaps', to='seo_ai.gappipelinerun')),
            ],
            options={
                'ordering': ('run', '-priority'),
                'indexes': [models.Index(fields=['run', '-priority'], name='seo_ai_gapc_run_id_9b618b_idx')],
            },
        ),
        migrations.CreateModel(
            name='GapCitationAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('cited_url', models.URLField(max_length=2048)),
                ('cited_domain', models.CharField(blank=True, default='', max_length=255)),
                ('is_ours', models.BooleanField(db_index=True, default=False)),
                ('matched_url', models.URLField(blank=True, default='', max_length=2048)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('method', models.CharField(default='url_exact', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='seo_ai.gapllmresult')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citation_attributions', to='seo_ai.gappipelinerun')),
            ],
            options={
                'ordering': ('run', '-match_confidence'),
                'indexes': [models.Index(fields=['run', 'is_ours'], name='seo_ai_gapc_run_id_3ad3a7_idx')],
            },
        ),
    ]
