# Generated by Django 6.0.2 on 2026-02-25 09:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_demand', 'On-Demand'), ('url_inspection', 'URL Inspection')], db_index=True, default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_urls_discovered', models.PositiveIntegerField(default=0)),
                ('total_urls_crawled', models.PositiveIntegerField(default=0)),
                ('total_urls_failed', models.PositiveIntegerField(default=0)),
                ('total_urls_skipped', models.PositiveIntegerField(default=0)),
                ('max_depth_reached', models.PositiveIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('error_summary', models.JSONField(blank=True, default=dict, help_text='Summary of errors: {error_type: count}')),
                ('target_url', models.URLField(blank=True, default='', help_text='Target URL for url_inspection sessions', max_length=2048)),
                ('target_path_prefix', models.CharField(blank=True, default='', help_text='Path prefix for sectional crawls (e.g. /blog/)', max_length=500)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_sessions', to='crawler.website')),
            ],
            options={
                'db_table': 'crawl_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=2048)),
                ('target_url', models.URLField(db_index=True, max_length=2048)),
                ('link_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('media', 'Media'), ('resource', 'Resource')], default='internal', max_length=20)),
                ('anchor_text', models.TextField(blank=True, default='')),
                ('rel_attributes', models.CharField(blank=True, default='', help_text='Rel attribute values (nofollow, sponsored, ugc, etc.)', max_length=200)),
                ('is_navigation', models.BooleanField(default=False, help_text='Whether this link is part of site navigation')),
                ('crawl_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='crawl_sessions.crawlsession')),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('normalized_url', models.URLField(blank=True, default='', max_length=2048)),
                ('http_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_url', models.URLField(blank=True, default='', help_text='Destination URL after all redirects', max_length=2048)),
                ('redirect_chain', models.JSONField(blank=True, default=list, help_text='Ordered list of redirect hops')),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('h1', models.TextField(blank=True, default='')),
                ('h2_list', models.JSONField(blank=True, default=list)),
                ('h3_list', models.JSONField(blank=True, default=list)),
                ('canonical_url', models.URLField(blank=True, default='', max_length=2048)),
                ('robots_meta', models.CharField(blank=True, default='', help_text='Robots meta tag directives (e.g. noindex, nofollow)', max_length=200)),
                ('crawl_depth', models.PositiveSmallIntegerField(default=0)),
                ('load_time_ms', models.FloatField(blank=True, null=True)),
                ('content_size_bytes', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_https', models.BooleanField(default=False)),
                ('page_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of page content for change detection', max_length=64)),
                ('source', models.CharField(choices=[('seed', 'Seed URL'), ('sitemap', 'Sitemap'), ('link', 'Discovered Link'), ('canonical', 'Canonical Tag'), ('redirect', 'Redirect Target'), ('manual', 'Manual Entry')], default='link', max_length=20)),
                ('crawl_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('images_without_alt', models.PositiveIntegerField(default=0)),
                ('crawl_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='crawl_sessions.crawlsession')),
            ],
            options={
                'db_table': 'pages',
            },
        ),
        migrations.CreateModel(
            name='SitemapURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sitemap_source', models.URLField(help_text='The sitemap file URL this was found in', max_length=2048)),
                ('page_url', models.URLField(db_index=True, max_length=2048)),
                ('lastmod', models.DateTimeField(blank=True, null=True)),
                ('changefreq', models.CharField(blank=True, default='', max_length=20)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('crawl_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_urls', to='crawl_sessions.crawlsession')),
            ],
            options={
                'db_table': 'sitemap_urls',
            },
        ),
        migrations.CreateModel(
            name='StructuredData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_type', models.CharField(help_text='Detected schema type (e.g. FAQ, Product, Article)', max_length=100)),
                ('raw_json', models.JSONField(blank=True, default=dict, help_text='Raw JSON-LD data block')),
                ('is_valid', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_data', to='crawl_sessions.page')),
            ],
            options={
                'db_table': 'structured_data',
            },
        ),
        migrations.CreateModel(
            name='URLClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(db_index=True, max_length=2048)),
                ('classification', models.CharField(choices=[('indexed_candidate', 'Indexed Candidate'), ('crawled_not_indexed', 'Crawled – Not Indexed'), ('discovered_not_crawled', 'Discovered – Not Crawled'), ('redirected', 'Redirected Page'), ('not_found_404', 'Not Found (404)'), ('soft_404', 'Soft 404'), ('duplicate_without_canonical', 'Duplicate without Canonical'), ('alternate_with_canonical', 'Alternate with Proper Canonical'), ('excluded_noindex', 'Excluded by Noindex'), ('blocked_by_robots', 'Blocked by Robots'), ('server_error_5xx', 'Server Error (5xx)')], db_index=True, max_length=40)),
                ('reason', models.TextField(blank=True, default='', help_text='Human-readable explanation for this classification')),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('crawl_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_classifications', to='crawl_sessions.crawlsession')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='crawl_sessions.page')),
            ],
            options={
                'db_table': 'url_classifications',
            },
        ),
        migrations.AddIndex(
            model_name='crawlsession',
            index=models.Index(fields=['website', 'status'], name='crawl_sessi_website_cdf717_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlsession',
            index=models.Index(fields=['website', 'session_type', '-started_at'], name='crawl_sessi_website_9ce778_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['crawl_session', 'link_type'], name='links_crawl_s_06d92a_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['crawl_session', 'source_url'], name='links_crawl_s_4d867d_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['crawl_session', 'http_status_code'], name='pages_crawl_s_2b036e_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['crawl_session', 'crawl_depth'], name='pages_crawl_s_8eb30d_idx'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('crawl_session', 'url'), name='unique_session_url'),
        ),
        migrations.AddIndex(
            model_name='sitemapurl',
            index=models.Index(fields=['crawl_session', 'page_url'], name='sitemap_url_crawl_s_e3bd0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='urlclassification',
            constraint=models.UniqueConstraint(fields=('crawl_session', 'url'), name='unique_classification_session_url'),
        ),
    ]
