# Generated by Django 5.2.11 on 2026-03-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlsession',
            name='exclusion_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Count of excluded URLs by lifecycle state'),
        ),
        migrations.AddField(
            model_name='crawlsession',
            name='total_excluded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlsession',
            name='total_index_eligible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlsession',
            name='total_urls_queued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlsession',
            name='total_urls_rendered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='canonical_match',
            field=models.BooleanField(default=True, help_text='Does declared match resolved canonical?'),
        ),
        migrations.AddField(
            model_name='page',
            name='canonical_resolved',
            field=models.URLField(blank=True, default='', help_text='The true canonical resolved by the crawler', max_length=2048),
        ),
        migrations.AddField(
            model_name='page',
            name='directory_segment',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Top-level subfolder path', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='discovery_source_first',
            field=models.CharField(blank=True, default='', help_text='Where this URL was initially discovered', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='discovery_sources_all',
            field=models.JSONField(blank=True, default=list, help_text='All methods by which this URL was discovered'),
        ),
        migrations.AddField(
            model_name='page',
            name='page_template',
            field=models.CharField(blank=True, default='', help_text='Identified page layout or framework template', max_length=100),
        ),
        migrations.AddField(
            model_name='page',
            name='url_lifecycle_state',
            field=models.CharField(choices=[('discovered_not_crawled', 'Discovered – currently not crawled'), ('crawled_not_indexed', 'Crawled – currently not indexed'), ('index_eligible', 'Indexable / Indexed Candidate'), ('alternate_with_canonical', 'Alternate page with proper canonical tag'), ('duplicate_not_selected', 'Duplicate without user-selected canonical'), ('not_found', 'Not found (404)'), ('soft_404', 'Soft 404'), ('blocked_by_robots', 'Blocked by robots.txt'), ('excluded_by_noindex', 'Excluded by ‘noindex’ tag'), ('server_error', 'Server error (5xx)'), ('redirect', 'Page with redirect'), ('crawl_anomaly', 'Crawl anomaly')], db_index=True, default='discovered_not_crawled', max_length=40),
        ),
        migrations.AddField(
            model_name='structureddata',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, help_text='List of missing/invalid schema properties'),
        ),
        migrations.AddField(
            model_name='structureddata',
            name='validation_state',
            field=models.CharField(choices=[('valid', 'Valid'), ('warning', 'Valid with Warnings'), ('invalid', 'Invalid')], default='valid', max_length=20),
        ),
    ]
