# Generated by Django 5.2.12 on 2026-05-07 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_sessions', '0002_crawlsession_exclusion_breakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('crawl', 'Crawled'), ('discovery', 'Discovery'), ('skip', 'Skipped'), ('error', 'Error'), ('blocked', 'Blocked'), ('redirect', 'Redirect'), ('session', 'Session')], db_index=True, max_length=20)),
                ('url', models.CharField(blank=True, default='', help_text='Target URL for the event (empty for session-level events)', max_length=2048)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('crawl_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crawl_sessions.crawlsession')),
            ],
            options={
                'db_table': 'crawl_events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['crawl_session', '-timestamp'], name='crawl_event_crawl_s_b99ae9_idx')],
            },
        ),
    ]
