# Generated by Django 5.2.12 on 2026-05-07 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl_sessions', '0003_add_crawlevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('urls.csv', 'URLs (CSV)'), ('issues.xlsx', 'Issues (CSV)'), ('sitemap.xml', 'Sitemap (XML)'), ('broken-links.csv', 'Broken Links (CSV)'), ('redirects.csv', 'Redirects (CSV)'), ('metadata.json', 'Metadata (JSON)')], db_index=True, max_length=32)),
                ('content', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('crawl_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='crawl_sessions.crawlsession')),
            ],
            options={
                'db_table': 'export_records',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['crawl_session', '-generated_at'], name='export_reco_crawl_s_8ebf20_idx')],
            },
        ),
    ]
